import type { SourceNote } from "./types";
import publishedSourceNotesStore from "./generated/published-source-notes.json";

const baseSourceNotes: SourceNote[] = [
  {
    id: "OC101-001",
    title: "OpenClaw 101 仓库结构与来源分类法",
    siteName: "GitHub / openclaw101",
    sourceUrl: "https://github.com/mengjian-github/openclaw101",
    contentType: "source_map",
    boardFit: ["care", "extension", "dialogue", "opc"],
    summary:
      "最适合拿来做 AuraClaw 的来源索引和内容分类参考。它把资源拆成官方、入门部署、平台接入、技能开发、视频、深度文章、工具与插件、云平台部署、玩法与场景。",
    keyPoints: [
      "resources.ts 是整站资源数据库，适合反哺 AuraClaw 的来源地图",
      "content/days 是 7 天学习路径，适合拿来做起步路线骨架",
      "getting-started.mdx 适合做最小入门叙事参考",
    ],
    recommendedFor: ["内容来源整理", "起步路线设计", "平台接入梳理"],
    newbieFriendly: true,
    needsManualReview: false,
    citationMode: "structured_rewrite",
    reuseTargets: ["track_page", "recipe_page", "source_index"],
    lastChecked: "2026-04-08",
    notes: "不适合整站搬运，更适合作为“来源的来源”，帮 AuraClaw 继续长内容。",
  },
  {
    id: "OC101-002",
    title: "第 1 天：初识 OpenClaw",
    siteName: "GitHub / openclaw101",
    sourceUrl: "https://github.com/mengjian-github/openclaw101/blob/main/content/days/day1.md",
    contentType: "learning_path",
    boardFit: ["care"],
    summary:
      "最值得借鉴的是“先建立 AI 助手心智，再进入安装和能力”这个顺序。它很适合反哺 AuraClaw 的 30 分钟起步包。",
    keyPoints: [
      "先区分 AI 助手和聊天机器人",
      "先让用户想清楚自己每天重复做的事",
      "第一天不强调配置，而强调目标和预期",
    ],
    recommendedFor: ["30 分钟起步包", "产后护理路线图"],
    newbieFriendly: true,
    needsManualReview: false,
    citationMode: "summary",
    reuseTargets: ["track_page", "recipe_page", "source_index"],
    lastChecked: "2026-04-08",
    notes: "适合拿“用户心智顺序”，不适合直接沿用人格化叙事。",
  },
  {
    id: "OC101-003",
    title: "第 4 天：接入你的数字生活",
    siteName: "GitHub / openclaw101",
    sourceUrl: "https://github.com/mengjian-github/openclaw101/blob/main/content/days/day4.md",
    contentType: "learning_path",
    boardFit: ["care", "extension"],
    summary:
      "这一天的价值在于它明确把 Gmail、日历、搜索、浏览器能力放在“从能聊天到能办事”的转折点，很适合反哺 AuraClaw 的能力扩展和平台接入叙事。",
    keyPoints: [
      "能力扩展的本质是给 OpenClaw 接上手和眼睛",
      "Gmail、Calendar、Search、Browser 是从玩具到工具的分水岭",
      "先接入，再测试，再进入真实工作流",
    ],
    recommendedFor: ["飞书 / 钉钉 / 企微接入后的第一条工作流", "浏览器控制与抓取增强"],
    newbieFriendly: true,
    needsManualReview: false,
    citationMode: "structured_rewrite",
    reuseTargets: ["track_page", "recipe_page", "source_index"],
    lastChecked: "2026-04-08",
    notes: "这条不直接等于平台接入教程，但很适合拿来做“接入后的第一步”。",
  },
  {
    id: "OC101-004",
    title: "第 7 天：进阶玩法与成长路线",
    siteName: "GitHub / openclaw101",
    sourceUrl: "https://github.com/mengjian-github/openclaw101/blob/main/content/days/day7.md",
    contentType: "learning_path",
    boardFit: ["opc", "extension"],
    summary:
      "适合拿来做 AuraClaw 后半段的长期成长路线。重点不是“毕业”，而是把技能、自定义能力、多设备协作、长期成长放进一条顺的进阶路径里。",
    keyPoints: [
      "先回顾 7 天旅程，再进入进阶玩法",
      "自定义 Skill 是成长路线的一部分",
      "Nodes、多设备协作和长期扩展适合放在更后面",
    ],
    recommendedFor: ["一人内容公司骨架", "一人情报公司骨架", "长期成长路线"],
    newbieFriendly: false,
    needsManualReview: false,
    citationMode: "summary",
    reuseTargets: ["track_page", "recipe_page", "source_index"],
    lastChecked: "2026-04-08",
    notes: "很适合做 OPC 的“毕业后继续养大”的路线提示。",
  },
  {
    id: "OC101-005",
    title: "腾讯云 — OpenClaw 接入飞书保姆级教程",
    siteName: "腾讯云",
    sourceUrl: "https://cloud.tencent.com/developer/article/2625073",
    contentType: "tutorial",
    boardFit: ["care"],
    summary: "这是目前最适合反哺 AuraClaw“飞书接入后第一条工作流”的中文平台接入来源之一。",
    keyPoints: ["覆盖 Lighthouse 一键部署", "覆盖飞书机器人接入全流程", "适合作为中文协作工作流的前置来源"],
    recommendedFor: ["飞书接入", "中文协作场景"],
    newbieFriendly: true,
    needsManualReview: true,
    citationMode: "summary",
    reuseTargets: ["recipe_page", "source_index"],
    lastChecked: "2026-04-08",
    notes: "最适合支持“先判断接入状态，再跑第一条团队同步工作流”。",
  },
  {
    id: "OC101-006",
    title: "阿里云 — 部署 OpenClaw 构建钉钉 AI 助理",
    siteName: "阿里云",
    sourceUrl: "https://help.aliyun.com/zh/simple-application-server/use-cases/quickly-deploy-and-use-openclaw",
    contentType: "tutorial",
    boardFit: ["care"],
    summary: "适合支持钉钉方向的平台接入说明，尤其适合国内用户的轻量服务器部署路径。",
    keyPoints: ["一键部署", "可视化配置面板", "钉钉接入"],
    recommendedFor: ["钉钉接入", "平台接入说明"],
    newbieFriendly: true,
    needsManualReview: true,
    citationMode: "summary",
    reuseTargets: ["recipe_page", "source_index"],
    lastChecked: "2026-04-08",
    notes: "很适合和飞书、企微来源一起组成“中文平台接入三件套”。",
  },
  {
    id: "OC101-007",
    title: "阿里云 — AppFlow 集成企业微信",
    siteName: "阿里云",
    sourceUrl: "https://help.aliyun.com/zh/simple-application-server/use-cases/openclaw-enterprise-wechat-integration",
    contentType: "tutorial",
    boardFit: ["care"],
    summary: "适合支持企微接入方向，尤其适合企业协作和群聊直接交互场景。",
    keyPoints: ["企业微信接入", "AppFlow 连接器", "适合企业协作"],
    recommendedFor: ["企业微信接入", "中文平台协作"],
    newbieFriendly: true,
    needsManualReview: true,
    citationMode: "summary",
    reuseTargets: ["recipe_page", "source_index"],
    lastChecked: "2026-04-08",
    notes: "对 AuraClaw 的价值不是整篇教程，而是“企微这条路怎么纳入第一条工作流”。",
  },
  {
    id: "OC101-008",
    title: "OpenClaw 7 天入门指南 — 飞书知识库",
    siteName: "OpenClaw 101",
    sourceUrl: "https://my.feishu.cn/wiki/YkWgwqSchi9xW3kEuZscAm0lnFf",
    contentType: "learning_path",
    boardFit: ["care", "extension", "opc"],
    summary: "是 openclaw101 仓库外部承载的系统化学习路径来源，适合 AuraClaw 拿来做长期成长路线索引。",
    keyPoints: ["每天一个主题", "从认识到进阶的系统化路径", "适合作为继续深挖的延伸来源"],
    recommendedFor: ["学习路径索引", "起步路线", "进阶路线"],
    newbieFriendly: true,
    needsManualReview: true,
    citationMode: "link",
    reuseTargets: ["source_index"],
    lastChecked: "2026-04-08",
    notes: "适合做 AuraClaw 的“继续阅读”来源，不适合取代 AuraClaw 自己的经验包。",
  },
  {
    id: "OC101-009",
    title: "搬主题 — 一键安装部署超详细图文教程",
    siteName: "搬主题",
    sourceUrl: "https://www.banzhuti.com/openclaw-moltbot-clawdbot-tutorial.html",
    contentType: "tutorial",
    boardFit: ["care"],
    summary: "非常适合支持“飞书 / 钉钉 / 微信 / Web”这类国内平台集成的路径判断。",
    keyPoints: ["四种集成方式", "国内用户友好", "图文说明完整"],
    recommendedFor: ["平台接入说明", "中文协作入口"],
    newbieFriendly: true,
    needsManualReview: true,
    citationMode: "summary",
    reuseTargets: ["recipe_page", "source_index"],
    lastChecked: "2026-04-08",
    notes: "很适合拿来补“如果平台还没接好，最小建议该怎么说”。",
  },
  {
    id: "OC101-010",
    title: "菜鸟教程 — OpenClaw（Clawdbot）完整教程",
    siteName: "菜鸟教程",
    sourceUrl: "https://www.runoob.com/ai-agent/openclaw-clawdbot-tutorial.html",
    contentType: "tutorial",
    boardFit: ["care"],
    summary: "很适合作为中文起步路径的补充来源，尤其适合帮助 AuraClaw 补最小安装和开发模式描述。",
    keyPoints: ["从源码拉取到 build 的完整过程", "涵盖开发模式", "中文新手可读性较强"],
    recommendedFor: ["30 分钟起步包", "安装说明补充"],
    newbieFriendly: true,
    needsManualReview: true,
    citationMode: "summary",
    reuseTargets: ["recipe_page", "source_index"],
    lastChecked: "2026-04-08",
    notes: "不适合大段照搬，更适合拿来补“用户如果没装稳，下一步该查什么”。",
  },
  {
    id: "OC101-011",
    title: "阿里云百炼 — OpenClaw 接入指南",
    siteName: "阿里云百炼",
    sourceUrl: "https://help.aliyun.com/zh/model-studio/openclaw",
    contentType: "tutorial",
    boardFit: ["extension", "opc"],
    summary: "这是很有价值的国内模型接入来源，适合支持 AuraClaw 后续的能力扩展和进阶路线。",
    keyPoints: ["Qwen / DeepSeek / Kimi 等模型接入", "dashboard 配置", "地域差异说明"],
    recommendedFor: ["模型接入", "国内用户路径"],
    newbieFriendly: false,
    needsManualReview: true,
    citationMode: "summary",
    reuseTargets: ["recipe_page", "source_index"],
    lastChecked: "2026-04-08",
    notes: "适合放进后续“能力扩展”或“长期成长路线”，不建议作为第一次成功的起步内容。",
  },
  {
    id: "OC101-012",
    title: "GitHub — 哈喽！龙虾（Hello Claw）",
    siteName: "GitHub",
    sourceUrl: "https://github.com/datawhalechina/hello-claw",
    contentType: "guide",
    boardFit: ["care", "extension"],
    summary: "这是体系化中文开源教程，适合做 AuraClaw 的中文来源补充，尤其适合“领养第一只 Claw”这种起步心智。",
    keyPoints: ["DataWhale 出品", "中文体系化开源教程", "覆盖架构、Skills、平台接入和部署"],
    recommendedFor: ["中文起步路线", "学习路径索引"],
    newbieFriendly: true,
    needsManualReview: true,
    citationMode: "summary",
    reuseTargets: ["source_index", "track_page"],
    lastChecked: "2026-04-08",
    notes: "更适合作为 AuraClaw 的“继续学习”来源，不适合直接替代 AuraClaw 的经验包。",
  },
  {
    id: "OC101-013",
    title: "飞书官方 — 一文完全搞懂 Clawd Bot",
    siteName: "飞书官网",
    sourceUrl: "https://www.feishu.cn/content/article/7602519239445974205",
    contentType: "deep_dive",
    boardFit: ["extension", "opc"],
    summary: "非常适合反哺 AuraClaw 的架构理解、安全提醒和团队协作视角，尤其适合中文平台接入后的进一步说明。",
    keyPoints: ["Gateway-Node 架构", "安全团队视角", "部署方案与成本分析"],
    recommendedFor: ["能力扩展说明", "进阶理解", "团队协作场景"],
    newbieFriendly: false,
    needsManualReview: true,
    citationMode: "summary",
    reuseTargets: ["recipe_page", "source_index"],
    lastChecked: "2026-04-08",
    notes: "适合做进阶补充，不适合做起步内容。",
  },
  {
    id: "AOT-001",
    title: "awesome-openclaw-tutorial — 30 秒快速选择部署方案",
    siteName: "GitHub / awesome-openclaw-tutorial",
    sourceUrl: "https://github.com/xianyu110/awesome-openclaw-tutorial",
    contentType: "decision_map",
    boardFit: ["care", "extension"],
    summary:
      "最适合拿来做国内用户的第一步分流。它把不同用户类型和部署方案快速对应起来，适合反哺 AuraClaw 的起步分流与国内路径选择。",
    keyPoints: [
      "先按用户类型分流，而不是先抛一堆部署术语",
      "把不同部署方案压成快速选择题，而不是大而全教程",
      "特别适合国内用户的低门槛入门判断",
    ],
    recommendedFor: ["Starter Pack 分流", "国内路径选择", "起步路线"],
    newbieFriendly: true,
    needsManualReview: true,
    citationMode: "structured_rewrite",
    reuseTargets: ["source_index", "recipe_page"],
    lastChecked: "2026-04-08",
    notes: "适合拿结构，不适合直接搬运整张部署对比表。",
  },
  {
    id: "AOT-002",
    title: "awesome-openclaw-tutorial — 7 天学习路径",
    siteName: "GitHub / awesome-openclaw-tutorial",
    sourceUrl: "https://github.com/xianyu110/awesome-openclaw-tutorial/blob/main/LEARNING-PATH.md",
    contentType: "learning_path",
    boardFit: ["care", "extension", "opc"],
    summary:
      "很适合拿来强化 AuraClaw 的学习节奏，尤其是第 4 天多平台集成、第 6 天自动化和第 7 天实战项目这条线。",
    keyPoints: [
      "第 4 天聚焦多平台集成",
      "第 6 天聚焦定时任务和网站监控",
      "第 7 天聚焦实战项目与经验总结",
    ],
    recommendedFor: ["平台接入", "自动化工作流", "OPC 成长路线"],
    newbieFriendly: true,
    needsManualReview: true,
    citationMode: "summary",
    reuseTargets: ["source_index", "track_page", "recipe_page"],
    lastChecked: "2026-04-08",
    notes: "适合拿节奏与章节顺序，不适合直接搬章节正文。",
  },
  {
    id: "AOT-003",
    title: "awesome-openclaw-tutorial — examples 自动化示例",
    siteName: "GitHub / awesome-openclaw-tutorial",
    sourceUrl: "https://github.com/xianyu110/awesome-openclaw-tutorial/tree/main/examples",
    contentType: "example_pack",
    boardFit: ["extension", "opc"],
    summary:
      "examples 目录里最有价值的不是配置文件本身，而是它已经给出了 daily-report.sh、website-monitor.sh、feishu-config.json 这类可改写成 AuraClaw 经验包的题材。",
    keyPoints: [
      "daily-report.sh 适合反哺 AI 日报或团队日报工作流",
      "website-monitor.sh 适合反哺网站变更监控提醒",
      "feishu-config.json 适合支持平台接入题材",
    ],
    recommendedFor: ["网站监控", "日报自动化", "平台接入经验包"],
    newbieFriendly: false,
    needsManualReview: true,
    citationMode: "structured_rewrite",
    reuseTargets: ["source_index", "recipe_page"],
    lastChecked: "2026-04-08",
    notes: "非常适合做经验包题材库，但不适合把脚本原文直接放进站里。",
  },
  {
    id: "AOT-004",
    title: "awesome-openclaw-tutorial — 小白一键部署教程",
    siteName: "GitHub / awesome-openclaw-tutorial",
    sourceUrl:
      "https://github.com/xianyu110/awesome-openclaw-tutorial/blob/main/Openclaw%E5%8F%B2%E4%B8%8A%E6%9C%80%E7%AE%80%E5%8D%95%E6%95%99%E7%A8%8B%EF%BC%8C%E5%B0%8F%E7%99%BD%E4%B8%80%E9%94%AE%E9%83%A8%E7%BD%B2.md",
    contentType: "tutorial",
    boardFit: ["care", "extension"],
    summary:
      "这篇教程最适合拿来支持国内用户的起步路径判断，因为它把飞书妙搭、宝塔、JVSClaw 等国内常见路线都纳进了同一个视角。",
    keyPoints: [
      "聚合了多条国内部署路线",
      "非常适合新手做路线判断",
      "适合支持“先选路，再配置”这类经验包",
    ],
    recommendedFor: ["国内部署路径", "起步路线判断", "平台接入前置"],
    newbieFriendly: true,
    needsManualReview: true,
    citationMode: "summary",
    reuseTargets: ["source_index", "recipe_page"],
    lastChecked: "2026-04-08",
    notes: "适合拿来做路径判断，不适合直接替代 AuraClaw 自己的经验包。",
  },
];

const publishedSourceNotes = ((publishedSourceNotesStore as { items?: Array<{ note?: SourceNote }> }).items ?? [])
  .map((item) => item.note)
  .filter((item): item is SourceNote => Boolean(item));

export const sourceNotes: SourceNote[] = [...publishedSourceNotes, ...baseSourceNotes];

export const featuredSourceNoteIds = ["OC101-002", "OC101-003", "AOT-001", "AOT-003"];
